name: Release build

on:
    release:
        types:
            - published

jobs:
    release-x64-debian-stretch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set release tag
              run: |
                echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
            - name: Setup QEMU
              uses: docker/setup-qemu-action@v1
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build
              uses: docker/build-push-action@v2
              with:
                context: debian-stretch
                file: debian-stretch/debian-stretch-cross.dockerfile
                platforms: linux/amd64
                push: true
                tags: it4smart/debian-stretch-cross:${{ env.RELEASE_TAG }}

    release-x64-debian-buster:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set release tag
              run: |
                echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
            - name: Setup QEMU
              uses: docker/setup-qemu-action@v1
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build
              uses: docker/build-push-action@v2
              with:
                context: debian-buster
                file: debian-buster/debian-buster-cross.dockerfile
                platforms: linux/amd64
                push: true
                tags: it4smart/debian-buster-cross:${{ env.RELEASE_TAG }}
  